services:
  - type: web
    name: arsip-backend
    runtime: node
    plan: free
    region: singapore
    branch: main
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
